<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ContractorBackend.Domain</RootNamespace>
    <AssemblyName>ContractorBackend.Domain</AssemblyName>
	  <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.12" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="5.0.12" />
  </ItemGroup>

</Project>
