<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>PersonnelBackend.Application</RootNamespace>
    <AssemblyName>PersonnelBackend.Application</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors>NU1605;</WarningsAsErrors>
	<Nullable>disable</Nullable>
    <NoWarn>1701;1702;1591</NoWarn>
    <IncludeOpenAPIAnalyzers>true</IncludeOpenAPIAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Institute\Queries\GetAllInstitute\**" />
    <EmbeddedResource Remove="Institute\Queries\GetAllInstitute\**" />
    <None Remove="Institute\Queries\GetAllInstitute\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="FluentValidation" Version="10.3.4" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.3.4" />
    <PackageReference Include="Gridify.EntityFramework" Version="2.4.4" />
    <PackageReference Include="Hangfire.Core" Version="1.7.27" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
    <PackageReference Include="MockQueryable.Moq" Version="5.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp.Serializers.SystemTextJson" Version="106.15.0" />
    <PackageReference Include="Serilog" Version="2.12.0" />
    <PackageReference Include="System.Globalization.Calendars" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Depandents\Queries\" />
    <Folder Include="Examination\Commands\" />
    <Folder Include="Institute\Commands\DeleteInstitute\" />
    <Folder Include="Institute\Queries\GetInstituteById\" />
    <Folder Include="Users\Commands\" />
  </ItemGroup>

</Project>
