
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>PersonnelBackend.Common</RootNamespace>
    <AssemblyName>PersonnelBackend.Common</AssemblyName>
	<Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DNTCommon.Web.Core" Version="2.9.5" />
    <PackageReference Include="DNTPersianUtils.Core" Version="5.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
