namespace ContractorBackend.Application.Mapping
{
    //public class UserDetailProfile : Profile
    //{
    //    public UserDetailProfile()
    //    {
    //        CreateMap<UserDetail, UserDetailDto>()
    //            .ForMember(d => d.Image, m => m.MapFrom(s => s.Image))
    //            .ForMember(d => d.CodBusun, m => m.MapFrom(s => s.CodBusun))
    //            .ForMember(d => d.DesBusun, m => m.MapFrom(s => s.DesBusun))
    //            .ForMember(d => d.CodCostCenter, m => m.MapFrom(s => s.CodCostCenter))
    //            .ForMember(d => d.DesCostCenter, m => m.MapFrom(s => s.DesCostCenter))
    //            .ForMember(d => d.CodSex, m => m.MapFrom(s => s.CodSex))
    //            .ForMember(d => d.DesSex, m => m.MapFrom(s => s.DesSex))
    //            .ForMember(d => d.CodMarid, m => m.MapFrom(s => s.CodMarid))
    //            .ForMember(d => d.DesMarid, m => m.MapFrom(s => s.DesMarid))
    //            .ForMember(d => d.ChildCount, m => m.MapFrom(s => s.ChildCount))
    //            .ForMember(d => d.FatherName, m => m.MapFrom(s => s.FatherName))
    //            .ForMember(d => d.CodBirthPosition, m => m.MapFrom(s => s.CodBirthPosition))
    //            .ForMember(d => d.DesBirthPosition, m => m.MapFrom(s => s.DesBirthPosition))
    //            .ForMember(d => d.CodRegBirthPlacePosition, m => m.MapFrom(s => s.CodRegBirthPlacePosition))
    //            .ForMember(d => d.DesRegBirthPlacePosition, m => m.MapFrom(s => s.DesRegBirthPlacePosition))
    //            .ForMember(d => d.CrtyDate, m => m.MapFrom(s => s.CrtyDate))
    //            .ForMember(d => d.CrtNum, m => m.MapFrom(s => s.CrtNum))
    //            .ForMember(d => d.CrtSerNum, m => m.MapFrom(s => s.CrtSerNum))
    //            .ForMember(d => d.CodeNationaly, m => m.MapFrom(s => s.CodeNationaly))
    //            .ForMember(d => d.DesNationaly, m => m.MapFrom(s => s.DesNationaly))
    //            .ForMember(d => d.CodeReligion, m => m.MapFrom(s => s.CodeReligion))
    //            .ForMember(d => d.DesReligion, m => m.MapFrom(s => s.DesReligion))

    //            .ForMember(d => d.TellNum, m => m.MapFrom(s => long.Parse(s.TellNum ?? "0")))
    //            .ForMember(d => d.EmergencyTellNum, m => m.MapFrom(s => long.Parse(s.EmergencyTellNum ?? "0")))
    //            .ForMember(d => d.InternalTellNumFirst, m => m.MapFrom(s => int.Parse(s.InternalTellNumFirst ?? "0")))
    //            .ForMember(d => d.InternalTellNumSec, m => m.MapFrom(s => int.Parse(s.InternalTellNumSec ?? "0")))

    //            .ForMember(d => d.CodeArea, m => m.MapFrom(s => s.CodeArea))
    //            .ForMember(d => d.DesArea, m => m.MapFrom(s => s.DesArea))
    //            .ForMember(d => d.CodePost, m => m.MapFrom(s => s.CodePost))
    //            .ForMember(d => d.DesPost, m => m.MapFrom(s => s.DesPost))
    //            .ForMember(d => d.CodEmployedStatus, m => m.MapFrom(s => s.CodEmployedStatus))
    //            .ForMember(d => d.DesEmployedStatus, m => m.MapFrom(s => s.DesEmployedStatus))
    //            .ForMember(d => d.CodWorkTime, m => m.MapFrom(s => s.CodWorkTime))
    //            .ForMember(d => d.DesWorkTime, m => m.MapFrom(s => s.DesWorkTime))
    //            .ForMember(d => d.CodJob, m => m.MapFrom(s => s.CodJob))
    //            .ForMember(d => d.DesJob, m => m.MapFrom(s => s.DesJob))
    //            .ForMember(d => d.CodCategoryJob, m => m.MapFrom(s => s.CodCategoryJob))
    //            .ForMember(d => d.DesCategoryJob, m => m.MapFrom(s => s.DesCategoryJob))
    //            .ForMember(d => d.InYearsCount, m => m.MapFrom(s => s.InYearsCount))
    //            .ForMember(d => d.OutYearsCount, m => m.MapFrom(s => s.OutYearsCount))
    //            .ForMember(d => d.AllMatchYears, m => m.MapFrom(s => s.AllMatchYears))
    //            .ForMember(d => d.CodAssistance, m => m.MapFrom(s => s.CodAssistance))
    //            .ForMember(d => d.DesAssistance, m => m.MapFrom(s => s.DesAssistance))
    //            .ForMember(d => d.CodEmploymentType, m => m.MapFrom(s => s.CodEmploymentType))
    //            .ForMember(d => d.DesEmploymentType, m => m.MapFrom(s => s.DesEmploymentType))
    //            .ForMember(d => d.CodRecuitmentType, m => m.MapFrom(s => s.CodRecuitmentType))
    //            .ForMember(d => d.DesRecuitmentType, m => m.MapFrom(s => s.DesRecuitmentType))
    //            .ForMember(d => d.CodReward, m => m.MapFrom(s => s.CodReward))
    //            .ForMember(d => d.DesReward, m => m.MapFrom(s => s.DesReward))
    //            .ForMember(d => d.CodTeam, m => m.MapFrom(s => s.CodTeam))
    //            .ForMember(d => d.BusinessUnitId, m => m.MapFrom(s => s.BusinessUnitId))
    //            .ForMember(d => d.JobId, m => m.MapFrom(s => s.JobId))
    //            .ForMember(d => d.BusunMoavenatId, m => m.MapFrom(s => s.BusunMoavenatId))

    //            .ForMember(d => d.Sign, m => m.MapFrom(s => s.Sign))
    //            .ForAllOtherMembers(opt => opt.Ignore());

    //        CreateMap<UserInfoDto, UserDetail>()
    //                   .ForMember(d => d.Image, m => m.MapFrom(s => s.image_prsn_emply))
    //                   .ForMember(d => d.CodBusun, m => m.MapFrom(s => s.cod_busun_emply))
    //                   .ForMember(d => d.DesBusun, m => m.MapFrom(s => s.des_busun))
    //                   .ForMember(d => d.CodCostCenter, m => m.MapFrom(s => s.cod_cc_emply))
    //                   .ForMember(d => d.DesCostCenter, m => m.MapFrom(s => s.des_cc))
    //                   .ForMember(d => d.CodSex, m => m.MapFrom(s => s.lkp_cod_sex_emply))
    //                   .ForMember(d => d.DesSex, m => m.MapFrom(s => s.des_lkp_cod_sex_emply))
    //                   .ForMember(d => d.CodMarid, m => m.MapFrom(s => s.lkp_cod_mrid_emply))
    //                   .ForMember(d => d.DesMarid, m => m.MapFrom(s => s.des_lkp_cod_mrid_emply))
    //                   .ForMember(d => d.ChildCount, m => m.MapFrom(s => s.tot_child_emply))
    //                   .ForMember(d => d.FatherName, m => m.MapFrom(s => s.nam_fathr_emply))
    //                   .ForMember(d => d.CodBirthPosition, m => m.MapFrom(s => s.gepos_geographic_position_id_a))
    //                   .ForMember(d => d.DesBirthPosition, m => m.MapFrom(s => s.des_gepos_geog_position_id_a))
    //                   .ForMember(d => d.CodRegBirthPlacePosition, m => m.MapFrom(s => s.gepos_geographic_position_id_b))
    //                   .ForMember(d => d.DesRegBirthPlacePosition, m => m.MapFrom(s => s.des_gepos_geog_position_id_b))
    //                   .ForMember(d => d.CrtyDate, m => m.MapFrom(s => s.dat_crt_emply))
    //                   .ForMember(d => d.CrtNum, m => m.MapFrom(s => s.num_crt_emply))
    //                   .ForMember(d => d.CrtSerNum, m => m.MapFrom(s => s.num_ser_crt_emply))
    //                   .ForMember(d => d.CodeNationaly, m => m.MapFrom(s => s.lkp_cod_natlty_emply))
    //                   .ForMember(d => d.DesNationaly, m => m.MapFrom(s => s.des_lkp_cod_natlty_emply))
    //                   .ForMember(d => d.CodeReligion, m => m.MapFrom(s => s.lkp_cod_rlgn_emply))
    //                   .ForMember(d => d.DesReligion, m => m.MapFrom(s => s.des_lkp_cod_rlgn_emply))
    //                   .ForMember(d => d.TellNum, m => m.MapFrom(s => s.num_tel_emply.ToString()))
    //                   .ForMember(d => d.EmergencyTellNum, m => m.MapFrom(s => s.num_tel_emrgy_emply))
    //                   .ForMember(d => d.InternalTellNumFirst, m => m.MapFrom(s => s.num_tel_int_emply))
    //                   .ForMember(d => d.InternalTellNumSec, m => m.MapFrom(s => s.num_tel_int2_emply))
    //                   .ForMember(d => d.CodeArea, m => m.MapFrom(s => s.lkp_cod_area_busun))
    //                   .ForMember(d => d.DesArea, m => m.MapFrom(s => s.des_lkp_cod_area_busun))
    //                   .ForMember(d => d.CodePost, m => m.MapFrom(s => s.cod_post_emply))
    //                   .ForMember(d => d.DesPost, m => m.MapFrom(s => s.des_per_postd))
    //                   .ForMember(d => d.CodEmployedStatus, m => m.MapFrom(s => s.lkp_sta_emplt_emply))
    //                   .ForMember(d => d.DesEmployedStatus, m => m.MapFrom(s => s.des_lkp_sta_emplt_emply))
    //                   .ForMember(d => d.CodWorkTime, m => m.MapFrom(s => s.lkp_cod_wrktm))
    //                   .ForMember(d => d.DesWorkTime, m => m.MapFrom(s => s.des_wrktm))
    //                   .ForMember(d => d.CodJob, m => m.MapFrom(s => s.cod_job_emply))
    //                   .ForMember(d => d.DesJob, m => m.MapFrom(s => s.des_job))
    //                   .ForMember(d => d.CodCategoryJob, m => m.MapFrom(s => s.lkp_cod_class_job))
    //                   .ForMember(d => d.DesCategoryJob, m => m.MapFrom(s => s.des_lkp_cod_class_job))
    //                   .ForMember(d => d.InYearsCount, m => m.MapFrom(s => s.sen_int))
    //                   .ForMember(d => d.OutYearsCount, m => m.MapFrom(s => s.sen_out))
    //                   .ForMember(d => d.AllMatchYears, m => m.MapFrom(s => s.tatbigh_all))
    //                   .ForMember(d => d.CodAssistance, m => m.MapFrom(s => s.cod_movenat))
    //                   .ForMember(d => d.DesAssistance, m => m.MapFrom(s => s.des_movenat))
    //                   .ForMember(d => d.CodEmploymentType, m => m.MapFrom(s => s.pycnd_cod_sta_pycnd))
    //                   .ForMember(d => d.DesEmploymentType, m => m.MapFrom(s => s.des_pycnd))
    //                   .ForMember(d => d.CodRecuitmentType, m => m.MapFrom(s => s.lkp_cod_emplt_typ_emply))
    //                   .ForMember(d => d.DesRecuitmentType, m => m.MapFrom(s => s.des_cod_emplt))
    //                   .ForMember(d => d.CodReward, m => m.MapFrom(s => s.lkp_grp_obg_emply))
    //                   .ForMember(d => d.DesReward, m => m.MapFrom(s => s.des_lkp_grp_obg_emply))
    //                   .ForMember(d => d.CodTeam, m => m.MapFrom(s => s.num_team_teams))
    //                   .ForMember(d => d.BusinessUnitId, m => m.MapFrom(s => s.business_unit_id))
    //                   .ForMember(d => d.JobId, m => m.MapFrom(s => s.job_id))
    //                   .ForMember(d => d.BusunMoavenatId, m => m.MapFrom(s => s.id_busun_moavenat))
    //                   .ForMember(d => d.PositionId, m => m.MapFrom(s => s.position_id))
    //                   .ForMember(d => d.TeamId, m => m.MapFrom(s => s.team_id))
    //                   .ForMember(d => d.Sign, m => m.MapFrom(s => s.sign_prsn_emply))

    //                   .ForMember(d => d.BusunManageId, m => m.MapFrom(s => s.id_busun_manage))
    //                   .ForMember(d => d.CodManage, m => m.MapFrom(s => s.cod_manage))
    //                   .ForMember(d => d.DesManage, m => m.MapFrom(s => s.des_manage))
    //                   .ForAllOtherMembers(opt => opt.Ignore());



    //        CreateMap<UserInfoNoImageDto, UserDetail>()
    //            .ForMember(d => d.CodBusun, m => m.MapFrom(s => s.cod_busun_emply))
    //            .ForMember(d => d.DesBusun, m => m.MapFrom(s => s.des_busun))
    //            .ForMember(d => d.CodCostCenter, m => m.MapFrom(s => s.cod_cc_emply))
    //            .ForMember(d => d.DesCostCenter, m => m.MapFrom(s => s.des_cc))
    //            .ForMember(d => d.CodSex, m => m.MapFrom(s => s.lkp_cod_sex_emply))
    //            .ForMember(d => d.DesSex, m => m.MapFrom(s => s.des_lkp_cod_sex_emply))
    //            .ForMember(d => d.CodMarid, m => m.MapFrom(s => s.lkp_cod_mrid_emply))
    //            .ForMember(d => d.DesMarid, m => m.MapFrom(s => s.des_lkp_cod_mrid_emply))
    //            .ForMember(d => d.ChildCount, m => m.MapFrom(s => s.tot_child_emply))
    //            .ForMember(d => d.FatherName, m => m.MapFrom(s => s.nam_fathr_emply))
    //            .ForMember(d => d.CodBirthPosition, m => m.MapFrom(s => s.gepos_geographic_position_id_a))
    //            .ForMember(d => d.DesBirthPosition, m => m.MapFrom(s => s.des_gepos_geog_position_id_a))
    //            .ForMember(d => d.CodRegBirthPlacePosition, m => m.MapFrom(s => s.gepos_geographic_position_id_b))
    //            .ForMember(d => d.DesRegBirthPlacePosition, m => m.MapFrom(s => s.des_gepos_geog_position_id_b))
    //            .ForMember(d => d.CrtyDate, m => m.MapFrom(s => s.dat_crt_emply))
    //            .ForMember(d => d.CrtNum, m => m.MapFrom(s => s.num_crt_emply))
    //            .ForMember(d => d.CrtSerNum, m => m.MapFrom(s => s.num_ser_crt_emply))
    //            .ForMember(d => d.CodeNationaly, m => m.MapFrom(s => s.lkp_cod_natlty_emply))
    //            .ForMember(d => d.DesNationaly, m => m.MapFrom(s => s.des_lkp_cod_natlty_emply))
    //            .ForMember(d => d.CodeReligion, m => m.MapFrom(s => s.lkp_cod_rlgn_emply))
    //            .ForMember(d => d.DesReligion, m => m.MapFrom(s => s.des_lkp_cod_rlgn_emply))
    //            .ForMember(d => d.TellNum, m => m.MapFrom(s => s.num_tel_emply.ToString()))
    //            .ForMember(d => d.EmergencyTellNum, m => m.MapFrom(s => s.num_tel_emrgy_emply))
    //            .ForMember(d => d.InternalTellNumFirst, m => m.MapFrom(s => s.num_tel_int_emply))
    //            .ForMember(d => d.InternalTellNumSec, m => m.MapFrom(s => s.num_tel_int2_emply))
    //            .ForMember(d => d.CodeArea, m => m.MapFrom(s => s.lkp_cod_area_busun))
    //            .ForMember(d => d.DesArea, m => m.MapFrom(s => s.des_lkp_cod_area_busun))
    //            .ForMember(d => d.CodePost, m => m.MapFrom(s => s.cod_post_emply))
    //            .ForMember(d => d.DesPost, m => m.MapFrom(s => s.des_per_postd))
    //            .ForMember(d => d.CodEmployedStatus, m => m.MapFrom(s => s.lkp_sta_emplt_emply))
    //            .ForMember(d => d.DesEmployedStatus, m => m.MapFrom(s => s.des_lkp_sta_emplt_emply))
    //            .ForMember(d => d.CodWorkTime, m => m.MapFrom(s => s.lkp_cod_wrktm))
    //            .ForMember(d => d.DesWorkTime, m => m.MapFrom(s => s.des_wrktm))
    //            .ForMember(d => d.CodJob, m => m.MapFrom(s => s.cod_job_emply))
    //            .ForMember(d => d.DesJob, m => m.MapFrom(s => s.des_job))
    //            .ForMember(d => d.CodCategoryJob, m => m.MapFrom(s => s.lkp_cod_class_job))
    //            .ForMember(d => d.DesCategoryJob, m => m.MapFrom(s => s.des_lkp_cod_class_job))
    //            .ForMember(d => d.InYearsCount, m => m.MapFrom(s => s.sen_int))
    //            .ForMember(d => d.OutYearsCount, m => m.MapFrom(s => s.sen_out))
    //            .ForMember(d => d.AllMatchYears, m => m.MapFrom(s => s.tatbigh_all))
    //            .ForMember(d => d.CodAssistance, m => m.MapFrom(s => s.cod_movenat))
    //            .ForMember(d => d.DesAssistance, m => m.MapFrom(s => s.des_movenat))
    //            .ForMember(d => d.CodEmploymentType, m => m.MapFrom(s => s.pycnd_cod_sta_pycnd))
    //            .ForMember(d => d.DesEmploymentType, m => m.MapFrom(s => s.des_pycnd))
    //            .ForMember(d => d.CodRecuitmentType, m => m.MapFrom(s => s.lkp_cod_emplt_typ_emply))
    //            .ForMember(d => d.DesRecuitmentType, m => m.MapFrom(s => s.des_cod_emplt))
    //            .ForMember(d => d.CodReward, m => m.MapFrom(s => s.lkp_grp_obg_emply))
    //            .ForMember(d => d.DesReward, m => m.MapFrom(s => s.des_lkp_grp_obg_emply))
    //            .ForMember(d => d.CodTeam, m => m.MapFrom(s => s.num_team_teams))
    //            .ForMember(d => d.BusinessUnitId, m => m.MapFrom(s => s.business_unit_id))
    //            .ForMember(d => d.JobId, m => m.MapFrom(s => s.job_id))
    //            .ForMember(d => d.BusunMoavenatId, m => m.MapFrom(s => s.id_busun_moavenat))
    //            .ForMember(d => d.PositionId, m => m.MapFrom(s => s.position_id))
    //            .ForMember(d => d.TeamId, m => m.MapFrom(s => s.team_id))
    //            .ForMember(d => d.BusunManageId, m => m.MapFrom(s => s.id_busun_manage))
    //            .ForMember(d => d.CodManage, m => m.MapFrom(s => s.cod_manage))
    //            .ForMember(d => d.DesManage, m => m.MapFrom(s => s.des_manage))

    //            .ForAllOtherMembers(opt => opt.Ignore());


    //        CreateMap<UserDetail, UserInfoDto>()
    //            .ForMember(d => d.image_prsn_emply, m => m.MapFrom(s => s.Image))
    //            .ForMember(d => d.cod_busun_emply, m => m.MapFrom(s => s.CodBusun))
    //            .ForMember(d => d.des_busun, m => m.MapFrom(s => s.DesBusun))
    //            .ForMember(d => d.cod_cc_emply, m => m.MapFrom(s => s.CodCostCenter))
    //            .ForMember(d => d.des_cc, m => m.MapFrom(s => s.DesCostCenter))
    //            .ForMember(d => d.lkp_cod_sex_emply, m => m.MapFrom(s => s.CodSex))
    //            .ForMember(d => d.des_lkp_cod_sex_emply, m => m.MapFrom(s => s.DesSex))
    //            .ForMember(d => d.lkp_cod_mrid_emply, m => m.MapFrom(s => s.CodMarid))
    //            .ForMember(d => d.des_lkp_cod_mrid_emply, m => m.MapFrom(s => s.DesMarid))
    //            .ForMember(d => d.tot_child_emply, m => m.MapFrom(s => s.ChildCount))
    //            .ForMember(d => d.nam_fathr_emply, m => m.MapFrom(s => s.FatherName))
    //            .ForMember(d => d.gepos_geographic_position_id_a, m => m.MapFrom(s => s.CodBirthPosition))
    //            .ForMember(d => d.des_gepos_geog_position_id_a, m => m.MapFrom(s => s.DesBirthPosition))
    //            .ForMember(d => d.gepos_geographic_position_id_b, m => m.MapFrom(s => s.CodRegBirthPlacePosition))
    //            .ForMember(d => d.des_gepos_geog_position_id_b, m => m.MapFrom(s => s.DesRegBirthPlacePosition))
    //            .ForMember(d => d.dat_crt_emply, m => m.MapFrom(s => s.CrtyDate))
    //            .ForMember(d => d.num_crt_emply, m => m.MapFrom(s => s.CrtNum))
    //            .ForMember(d => d.num_ser_crt_emply, m => m.MapFrom(s => s.CrtSerNum))
    //            .ForMember(d => d.lkp_cod_natlty_emply, m => m.MapFrom(s => s.CodeNationaly))
    //            .ForMember(d => d.des_lkp_cod_natlty_emply, m => m.MapFrom(s => s.DesNationaly))
    //            .ForMember(d => d.lkp_cod_rlgn_emply, m => m.MapFrom(s => s.CodeReligion))
    //            .ForMember(d => d.des_lkp_cod_rlgn_emply, m => m.MapFrom(s => s.DesReligion))

    //            .ForMember(d => d.num_tel_emply, m => m.MapFrom(s => long.Parse(s.TellNum ?? "0")))
    //            .ForMember(d => d.num_tel_emrgy_emply, m => m.MapFrom(s => long.Parse(s.EmergencyTellNum ?? "0")))
    //            .ForMember(d => d.num_tel_int_emply, m => m.MapFrom(s => int.Parse(s.InternalTellNumFirst ?? "0")))
    //            .ForMember(d => d.num_tel_int2_emply, m => m.MapFrom(s => int.Parse(s.InternalTellNumSec ?? "0")))


    //            .ForMember(d => d.lkp_cod_area_busun, m => m.MapFrom(s => s.CodeArea))
    //            .ForMember(d => d.des_lkp_cod_area_busun, m => m.MapFrom(s => s.DesArea))
    //            .ForMember(d => d.cod_post_emply, m => m.MapFrom(s => s.CodePost))
    //            .ForMember(d => d.des_per_postd, m => m.MapFrom(s => s.DesPost))
    //            .ForMember(d => d.lkp_sta_emplt_emply, m => m.MapFrom(s => s.CodEmployedStatus))
    //            .ForMember(d => d.des_lkp_sta_emplt_emply, m => m.MapFrom(s => s.DesEmployedStatus))
    //            .ForMember(d => d.lkp_cod_wrktm, m => m.MapFrom(s => s.CodWorkTime))
    //            .ForMember(d => d.des_wrktm, m => m.MapFrom(s => s.DesWorkTime))
    //            .ForMember(d => d.cod_job_emply, m => m.MapFrom(s => s.CodJob))
    //            .ForMember(d => d.des_job, m => m.MapFrom(s => s.DesJob))
    //            .ForMember(d => d.lkp_cod_class_job, m => m.MapFrom(s => s.CodCategoryJob))
    //            .ForMember(d => d.des_lkp_cod_class_job, m => m.MapFrom(s => s.DesCategoryJob))
    //            .ForMember(d => d.sen_int, m => m.MapFrom(s => s.InYearsCount))
    //            .ForMember(d => d.sen_out, m => m.MapFrom(s => s.OutYearsCount))
    //            .ForMember(d => d.tatbigh_all, m => m.MapFrom(s => s.AllMatchYears))
    //            .ForMember(d => d.cod_movenat, m => m.MapFrom(s => s.CodAssistance))
    //            .ForMember(d => d.des_movenat, m => m.MapFrom(s => s.DesAssistance))
    //            .ForMember(d => d.lkp_cod_emplt_typ_emply, m => m.MapFrom(s => s.CodEmploymentType))
    //            .ForMember(d => d.des_pycnd, m => m.MapFrom(s => s.DesEmploymentType))
    //            .ForMember(d => d.lkp_cod_emplt_typ_emply, m => m.MapFrom(s => s.CodRecuitmentType))
    //            .ForMember(d => d.des_cod_emplt, m => m.MapFrom(s => s.DesRecuitmentType))
    //            .ForMember(d => d.lkp_grp_obg_emply, m => m.MapFrom(s => s.CodReward))
    //            .ForMember(d => d.des_lkp_grp_obg_emply, m => m.MapFrom(s => s.DesReward))
    //            .ForMember(d => d.num_team_teams, m => m.MapFrom(s => s.CodTeam))
    //            .ForMember(d => d.business_unit_id, m => m.MapFrom(s => s.BusinessUnitId))
    //            .ForMember(d => d.job_id, m => m.MapFrom(s => s.JobId))
    //            .ForMember(d => d.id_busun_moavenat, m => m.MapFrom(s => s.BusunMoavenatId))

    //            .ForMember(d => d.sign_prsn_emply, m => m.MapFrom(s => s.Sign))

    //                   .ForMember(d => d.id_busun_manage, m => m.MapFrom(s => s.BusunManageId))
    //                   .ForMember(d => d.cod_manage, m => m.MapFrom(s => s.CodManage))
    //                   .ForMember(d => d.des_manage, m => m.MapFrom(s => s.DesManage))

    //            .ForAllOtherMembers(opt => opt.Ignore());

    //        CreateMap<UserDetail, UserProfileDto>()
    //          .ForMember(d => d.image_prsn_emply, m => m.MapFrom(s => s.Image))
    //           .ForMember(d => d.des_busun, m => m.MapFrom(s => s.DesBusun))
    //           .ForMember(d => d.des_cc, m => m.MapFrom(s => s.DesCostCenter))
    //           .ForMember(d => d.des_lkp_cod_sex_emply, m => m.MapFrom(s => s.DesSex))
    //           .ForMember(d => d.lkp_cod_mrid_emply, m => m.MapFrom(s => s.CodMarid))
    //           .ForMember(d => d.des_lkp_cod_mrid_emply, m => m.MapFrom(s => s.DesMarid))
    //           .ForMember(d => d.tot_child_emply, m => m.MapFrom(s => s.ChildCount))
    //           .ForMember(d => d.nam_fathr_emply, m => m.MapFrom(s => s.FatherName))
    //           .ForMember(d => d.des_gepos_geog_position_id_a, m => m.MapFrom(s => s.DesBirthPosition))
    //           .ForMember(d => d.des_gepos_geog_position_id_b, m => m.MapFrom(s => s.DesRegBirthPlacePosition))
    //           .ForMember(d => d.dat_crt_emply, m => m.MapFrom(s => s.CrtyDate))
    //           .ForMember(d => d.num_crt_emply, m => m.MapFrom(s => s.CrtNum))
    //           .ForMember(d => d.num_ser_crt_emply, m => m.MapFrom(s => s.CrtSerNum))
    //           .ForMember(d => d.des_lkp_cod_natlty_emply, m => m.MapFrom(s => s.DesNationaly))
    //           .ForMember(d => d.des_lkp_cod_rlgn_emply, m => m.MapFrom(s => s.DesReligion))

    //           .ForMember(d => d.num_tel_emply, m => m.MapFrom(s => s.TellNum))
    //           .ForMember(d => d.num_tel_emrgy_emply, m => m.MapFrom(s => s.EmergencyTellNum))
    //           .ForMember(d => d.num_tel_int_emply, m => m.MapFrom(s => s.InternalTellNumFirst))
    //           .ForMember(d => d.num_tel_int2_emply, m => m.MapFrom(s => s.InternalTellNumSec))

    //           .ForMember(d => d.des_lkp_cod_area_busun, m => m.MapFrom(s => s.DesArea))
    //           .ForMember(d => d.cod_post_emply, m => m.MapFrom(s => s.CodePost))
    //           .ForMember(d => d.des_per_postd, m => m.MapFrom(s => s.DesPost))
    //           .ForMember(d => d.des_lkp_sta_emplt_emply, m => m.MapFrom(s => s.DesEmployedStatus))
    //           .ForMember(d => d.des_wrktm, m => m.MapFrom(s => s.DesWorkTime))
    //           .ForMember(d => d.des_job, m => m.MapFrom(s => s.DesJob))
    //           .ForMember(d => d.des_lkp_cod_class_job, m => m.MapFrom(s => s.DesCategoryJob))
    //           .ForMember(d => d.sen_int, m => m.MapFrom(s => s.InYearsCount))
    //           .ForMember(d => d.sen_out, m => m.MapFrom(s => s.OutYearsCount))
    //           .ForMember(d => d.tatbigh_all, m => m.MapFrom(s => s.AllMatchYears))
    //           .ForMember(d => d.des_movenat, m => m.MapFrom(s => s.DesAssistance))
    //           .ForMember(d => d.des_pycnd, m => m.MapFrom(s => s.DesEmploymentType))
    //           .ForMember(d => d.des_cod_emplt, m => m.MapFrom(s => s.DesRecuitmentType))
    //           .ForMember(d => d.des_lkp_grp_obg_emply, m => m.MapFrom(s => s.DesReward))
    //           .ForMember(d => d.num_team_teams, m => m.MapFrom(s => s.CodTeam))
    //           .ForAllOtherMembers(opt => opt.Ignore());

    //        CreateMap<UserDetail, UserVM>()
    //         .ForMember(d => d.DesCategoryJob, m => m.MapFrom(s => s.DesCategoryJob))
    //         .ForMember(d => d.DesCostCenter, m => m.MapFrom(s => s.DesCostCenter))
    //         .ForMember(d => d.InYearsCount, m => m.MapFrom(s => s.InYearsCount))
    //         .ForMember(d => d.OutYearsCount, m => m.MapFrom(s => s.OutYearsCount))
    //         .ForMember(d => d.AllMatchYears, m => m.MapFrom(s => s.AllMatchYears))
    //         .ForMember(d => d.DesSex, m => m.MapFrom(s => s.DesSex))
    //         .ForMember(d => d.DesAssistance, m => m.MapFrom(s => s.DesAssistance))
    //         .ForMember(d => d.DesPost, m => m.MapFrom(s => s.DesPost))
    //         .ForMember(d => d.ProfileImage, m => m.MapFrom(s => s.ProfileImage != null ? Convert.ToBase64String(s.ProfileImage) : string.Empty))
    //         .ForAllOtherMembers(x => x.Ignore());

    //        CreateMap<UserDetail, UserLovDto>() 
    //            ;

    //    }

    //}
}
